export default function Block(props) {
  const blockWidth = {
    width: props.style,
  };

  /*
The Block Component(s) are generated by the rowState. If there is a change in rowState, there is a re-rendering and then the Block components will be generated on the corresponding row that the user enters input into
  */

  return (
    <>
      <input
        className="marquee-block"
        // readOnly
        maxLength="1"
        type="text"
        style={blockWidth}
        value={props.block}
      />
    </>
  );
}
